version: '3.8'

services:
  db:
    image: postgres:16  # <--- CHANGED THIS
    container_name: khanpur_pos_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=khanpurpos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: